### PR TITLE
JUnit code + bug fixes

### LINKED ISSUE #9: Add products
As a business owner, I want to easily add new products to my inventory so that I can track my inventory.

### PR DESCRIPTION
**Pull request by EdmundTangg**
-Added newCommand JUnit tests
-Added getters for product and attribute classes
-Fixed newCommand pid bug

### CODE REVIEW

File: src/test/java/seedu/stockpal/commands/NewCommandTest.java [hunk 1]
```diff
@@ -1,13 +1,52 @@
...
+import seedu.stockpal.data.ProductList;
+import static org.junit.jupiter.api.Assertions.assertEquals;
+import static org.junit.jupiter.api.Assertions.assertNull;
 
-import static org.junit.jupiter.api.Assertions.assertTrue;
+public class NewCommandTest {
 
+    @Test
+    void newCommand_allFieldsFilled_expectCorrectAllocation() {
+        final ProductList productList = new ProductList();
```
Comment (Kobot7) [inline src/test/java/seedu/stockpal/commands/NewCommandTest.java]: Perhaps consider using @BeforeEach to do setup for every test case

File: src/main/java/seedu/stockpal/commands/NewCommand.java [hunk 2]
```diff
@@ -3,25 +3,30 @@
...
 
-
-
     public NewCommand(ProductList productList, String name, Integer quantity, Double price, String description) {
-        this.toAdd = new Product(name, quantity, price, description, pid++);
+        int pid;
+        if (productList.isEmpty()) {
+            pid = 1;
+        } else {
+            pid = productList.getSize() + 1;
```
Comment (Kobot7) [inline src/main/java/seedu/stockpal/commands/NewCommand.java]: Temporal fix, need to consider potential Pid overlap in the case that a product gets deleted

File: src/main/java/seedu/stockpal/commands/NewCommand.java [hunk 3]
```diff
@@ -3,25 +3,30 @@
...
+        }
+        this.toAdd = new Product(name, quantity, price, description, pid);
         this.productList = productList;
     }
 
     @Override
     public void execute() {
         productList.addProduct(toAdd);
-        System.out.println("Added product!");
+        printToScreen("Added product!");
```
Comment (Kobot7) [inline src/main/java/seedu/stockpal/commands/NewCommand.java]: Can consider making the string a constant in Common.java to avoid having magic literals

File: src/main/java/seedu/stockpal/data/product/Product.java [hunk 4]
```diff
@@ -17,25 +17,43 @@ public Product(String name, Integer quantity, Double price, String description,
...
 
     public Description getDescription() {
-        return description;
+        return this.description;
     }
 
     public Pid getPid() {
-        return pid;
+        return this.pid;
     }
```
Comment (NgYaoDong) [inline src/main/java/seedu/stockpal/data/product/Product.java]: Why are the methods doing repeated things?

File: src/main/java/seedu/stockpal/commands/NewCommand.java (hunk 2 above)
Comment (EdmundTangg) [reply src/main/java/seedu/stockpal/commands/NewCommand.java]: Considered product gets deleted case, fixed this issue.

File: src/main/java/seedu/stockpal/commands/NewCommand.java (hunk 3 above)
Comment (EdmundTangg) [reply src/main/java/seedu/stockpal/commands/NewCommand.java]: Fixed this.

**Comment by cheeseong2001** [comment]
LGTM

**Comment by leongxingyu** [comment]
LGTM.

**Comment by wjunjie01** [comment]
LGTM
